version: "3"
services:
  cqpweb:
   image: rahonabe/cqpweb
   hostname: CQPweb
   build: 
      context: ./CQPweb
   ports:
       - 8080:80
   volumes:
       - ${CORPORA}:/var/corpora
       - ${REGISTRY}:/usr/local/share/cwb/registry
       - ./volumes/cqpweb/upload:/var/cqpweb/upload
       - ./volumes/cqpweb/data:/var/www/html
       - ./volumes/cqpweb/tmp:/var/cqpweb/tmp
       - ./migration:/var/migration

  sql:
    image: mariadb
    hostname: sql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./volumes/sql/data:/var/lib/mysql
    volumes_from:
        - cqpweb
