version: "3"
services:
  cqpweb:
    image: rahonabe/cqpweb
    hostname: CQPweb
    environment:
      - APACHE_RUN_USER=${APACHE_RUN_USER}
      - APACHE_RUN_GROUP=${APACHE_RUN_GROUP}
      - APACHE_LOG_DIR=${APACHE_LOG_DIR}
      - APACHE_PID_FILE=${APACHE_PID_FILE}
      - APACHE_RUN_DIR=${APACHE_RUN_DIR}
      - REGISTRY_VOL=${REGISTRY_VOL}
      - WEB_ROOT=${WEB_ROOT}
      - APACHE_LOCK_DIR=${APACHE_LOCK_DIR}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - CQPWEB_ADMIN=${CQPWEB_ADMIN}
    build: 
      context: ./CQPweb
      args:
        - WEB_ROOT=${WEB_ROOT}
    ports:
       - 8080:80
    volumes:
       - ${CORPORA}:${CORPORA_VOL}
       - ${REGISTRY}:${REGISTRY_VOL}
       - upload:${UPLOAD_VOL}
       - tmp:${TMP_VOL}/var/cqpweb/tmp
  sql:
    image: mariadb
    hostname: sql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    volumes_from:
        - cqpweb


volumes:
  corpora:
    driver: local
  registry:
    driver: local
  upload:
    driver: local
  tmp:
    driver: local
  mysql:
    driver: local